spring:
  cloud:
    gateway:
      routes:
        #        - id: before_route
        #            uri: https://example.org
        #            predicates:
        #              - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
        - id: after_route
          uri: https://example.org
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
server:
  port: 8080